services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=52605851
      - POSTGRES_USER=osense
      - POSTGRES_DB=osense
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=johnchan@osensetech.com
      - PGADMIN_DEFAULT_PASSWORD=52605851
    ports:
      - "5050:80"
    restart: always

volumes:
  postgres_data: